import fs from 'fs/promises';
import path from 'path';
import { callClaude } from '../../utils/claude.js';
import { resolveSkills, loadSkillContents } from '../../engine/skill-resolver.js';
import { saveAgentOutput, parseFilesFromOutput, readSourceFiles } from '../../engine/output-store.js';
import { getWorkspacePath } from '../../utils/workspace.js';
import {
  DEPENDENCY_ALLOWLIST, validateDependencies, findUndeclaredImports,
  runCommand, parseTscErrors,
} from '../../utils/build-runner.js';
import * as out from '../../utils/output.js';

const AGENT_ID = 'assembler-agent';
const MAX_OUTPUT_TOKENS = 16_000; // glue set exceeds the 8k default on first generation

// Assembler: turns the accumulated output/src into a runnable app in prototype/.
// No LLM quality gate (gateResult: null) — the objective gate is that the result
// installs and typechecks. Build failures come back as syntaxErrors so the
// session-runner's existing retry loop drives the fix cycle.
export async function runAssemblerAgent({ session, pmFeedback = [], syntaxErrors = [] }) {
  out.divider();
  out.log(AGENT_ID, 'Assembling runnable prototype from output/src...');

  const source = await readSourceFiles({ tenantId: session.tenantId, projectId: session.projectId });
  if (!source) {
    out.warn(`[${AGENT_ID}] No source files in output/src — nothing to assemble.`);
    return { outputText: '', files: [], gateResult: null, syntaxErrors: [] };
  }

  const skillFilenames = await resolveSkills(AGENT_ID, 'assemble runnable prototype', session);
  session.agents[AGENT_ID].skillsLoaded = skillFilenames;
  const skillContent = await loadSkillContents(AGENT_ID, skillFilenames);

  const feedbackSection = pmFeedback.length > 0
    ? `\n\n## Previous Feedback\n${pmFeedback.join('\n')}`
    : '';

  const isRetry = syntaxErrors.length > 0;
  const syntaxSection = isRetry
    ? `\n\n## Build Errors to Fix\n${syntaxErrors.map(e => `${e.file} line ${e.line}: ${e.error}`).join('\n')}` +
      `\n\nOutput ONLY the files you are changing to fix these errors.`
    : '';

  const allowlist = [...DEPENDENCY_ALLOWLIST].join(', ');

  const systemPromptBase = `You are an Assembler Agent. You receive ALL source files generated by a multi-agent build. Your job is to make them RUN as one app, changing as little generated code as possible. Output ONLY the glue files (plus corrected copies of any generated file that must change), each preceded by: // filepath: {path}

Hard requirements:
1. package.json — scripts MUST be exactly: "dev": "concurrently -n api,web \\"npm:dev:api\\" \\"npm:dev:web\\"", "dev:api": "tsx src/server/index.ts", "dev:web": "vite", "typecheck": "tsc --noEmit". Dependencies ONLY from this allowlist: ${allowlist}. Pin known-good majors.
2. src/server/index.ts — Express entry point. Mount EVERY router found in the source. Read the port from process.env.API_PORT || 4000. Add a compatibility layer where routes disagree on paths or auth field names (e.g. req.user.id vs req.user.userId).
3. Database: NO real database. Use pg-mem, or in-memory maps if the code uses an ORM you cannot satisfy (e.g. replace a Sequelize config with a lightweight stub exposing the same model API surface the code uses). Infer the schema from the models/queries, create tables inline, seed 2-3 rows of demo data. If code requires a missing file like ../config/database, CREATE that file.
4. vite.config.ts — server: { port: Number(process.env.WEB_PORT) || 5173, proxy: { '/api': \`http://localhost:\${process.env.API_PORT || 4000}\` } } with the react plugin. Nothing else.
5. Frontend shell: index.html, src/main.tsx, src/App.tsx with routes to every generated page/component, plus any context/provider the components expect.
6. tsconfig.json: target ES2022, module ESNext, moduleResolution Bundler, jsx react-jsx, allowJs true, checkJs false, strict false, noEmit true, esModuleInterop true, skipLibCheck true, include ["src"].
7. Everything must typecheck with \`tsc --noEmit\`. Convert CommonJS files you must touch to ESM; leave working files alone.
8. Add a README.md at the prototype root: how to run, seeded demo logins, known gaps.`;

  const systemPrompt = skillContent
    ? `${systemPromptBase}\n\n${skillContent}`
    : systemPromptBase;

  const userPrompt =
    `## Generated source files\n${source}${feedbackSection}${syntaxSection}\n\n` +
    `Produce the glue files now.`;

  const response = await callClaude({
    systemPrompt,
    userPrompt,
    agentId: AGENT_ID,
    tenantId: session.tenantId,
    projectId: session.projectId,
    sessionId: session.sessionId,
    dryRun: session.dryRun,
    maxTokens: MAX_OUTPUT_TOKENS,
  });

  const outputText = response.content[0].text;
  const files = parseFilesFromOutput(outputText);
  if (files.length === 0) {
    return {
      outputText, files: [], gateResult: null,
      syntaxErrors: [{ file: 'output', line: 0, error: 'Assembler produced no // filepath: blocks' }],
    };
  }

  const workspacePath = getWorkspacePath(session.tenantId, session.projectId);
  const prototypeDir = path.join(workspacePath, 'prototype');

  // Copy-then-overlay: generated source first, then glue files overwrite on top.
  // Plain fs.cp — the copies are not agent output; only glue goes through
  // saveAgentOutput (with its caps and traversal guard).
  const srcDir = path.join(workspacePath, 'output', 'src');
  try {
    await fs.cp(srcDir, path.join(prototypeDir, 'src'), { recursive: true });
  } catch {
    // output/src may be empty on retries where only glue changed — fine.
  }

  await saveAgentOutput({
    tenantId: session.tenantId, projectId: session.projectId, files, subdir: 'prototype',
  });
  out.log(AGENT_ID, `Glue files saved to prototype/ (${files.length} file(s))`);

  // Dry run: no npm, no tsc — canned output is assumed good.
  if (session.dryRun) {
    return { outputText, files, gateResult: null, syntaxErrors: [] };
  }

  // --- Verification (never executes generated code) ---
  const pkgPath = path.join(prototypeDir, 'package.json');
  let pkgContent;
  try {
    pkgContent = await fs.readFile(pkgPath, 'utf8');
  } catch {
    return {
      outputText, files, gateResult: null,
      syntaxErrors: [{ file: 'package.json', line: 0, error: 'package.json missing from assembler output' }],
    };
  }

  let disallowed;
  try {
    disallowed = validateDependencies(pkgContent);
  } catch (err) {
    return {
      outputText, files, gateResult: null,
      syntaxErrors: [{ file: 'package.json', line: 0, error: `package.json is not valid JSON: ${err.message}` }],
    };
  }
  if (disallowed.length > 0) {
    return {
      outputText, files, gateResult: null,
      syntaxErrors: [{
        file: 'package.json', line: 0,
        error: `Disallowed dependencies: ${disallowed.join(', ')}. Use only: ${allowlist}`,
      }],
    };
  }

  // tsc skips .js files (checkJs off), so an import missing from package.json
  // would only crash at preview time, in front of the user. Catch it here and
  // let the retry loop drive the fix.
  const undeclared = await findUndeclaredImports(path.join(prototypeDir, 'src'), pkgContent);
  if (undeclared.length > 0) {
    out.warn(`[${AGENT_ID}] Undeclared imports: ${undeclared.map(u => u.packageName).join(', ')}`);
    return {
      outputText, files, gateResult: null,
      syntaxErrors: undeclared.map(u => ({
        file: u.file, line: 0,
        error: `imports '${u.packageName}' but package.json does not declare it — ` +
          (DEPENDENCY_ALLOWLIST.has(u.packageName)
            ? `add "${u.packageName}" to dependencies`
            : `'${u.packageName}' is not in the allowlist; rewrite the code to use an allowlisted package or no dependency`),
      })),
    };
  }

  out.log(AGENT_ID, 'npm install (--ignore-scripts)...');
  const install = await runCommand('npm install --ignore-scripts --no-audit --no-fund', { cwd: prototypeDir });
  if (install.code !== 0) {
    out.warn(`[${AGENT_ID}] npm install failed`);
    return { outputText, files, gateResult: null, syntaxErrors: parseTscErrors(install.output) };
  }

  out.log(AGENT_ID, 'Typechecking (tsc --noEmit)...');
  const typecheck = await runCommand('npx tsc --noEmit -p tsconfig.json', { cwd: prototypeDir });
  if (typecheck.code !== 0) {
    out.warn(`[${AGENT_ID}] Typecheck failed`);
    return { outputText, files, gateResult: null, syntaxErrors: parseTscErrors(typecheck.output) };
  }

  out.success(`[${AGENT_ID}] Prototype assembled and verified — start it from the web UI (Preview).`);
  return { outputText, files, gateResult: null, syntaxErrors: [] };
}
